name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d605787ea123f33ca9bfb3b0a61a2cfbf2f96c6ae4ae65036a79383fc1d6881e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
