name = "Minecat Neoforge"
author = "Kneelawk"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7deab370a01087b3bfb6a8d465c5b27cad20c03488cf16f5e9caad7d257ab86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.42"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
