name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a49a87762c764726b57c5ca5a0aaa4a7477d25d4e314be2b55b4aed742cf28ea"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
