name = "Minecat Neoforge"
author = "Kneelawk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e841023ac9caad759e033eaf664a32157f5d3ff8b325910616002612856dcc7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.39"

[options]
acceptable-game-versions = ["1.21"]
