name = "Minecat Neoforge"
author = "Kneelawk"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed2d4230d66f0cb298c3aa29c6b03662f3007bea69ce7afd89d8ecdaa24bceb1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.42"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
