name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f8325164eb6dbb0418173c400e9064ed8a30dbf0c42b2901f8b0f31b4898812"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
