name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "838cf2f839a3b6d2e330151cc0ae5144e87c9f50a1b95e9240bda672b237acb0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.42"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
