name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.4.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d05b6f4769cef58eaf9628807b524f0f5309567c5e8a8fe758333482879d0d1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
