name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a569b1ab16bd577d2994392197f3a23887d62d772caa415055c31f734079e602"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
