name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45060dbfb30ef93c8c32a6ee2dbfa890cfb7e35c5c99a1ea36b86c5a6de3ae16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.71"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
