name = "Minecat Neoforge"
author = "Kneelawk"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac311de8fe8d88462dcb39c39649aa618c84b3a3ca4c2aae49bd43d32c51707e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.42"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
