name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f9736449fb4eb461d2483d9c24df016cbbbc1176b08a40b21e1518a6c66df0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.42"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
