name = "Minecat Neoforge"
author = "Kneelawk"
version = "2.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12f43a51e0aba8e9f328b74737e25e79415edfba28f76429c82a3bb799912c62"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
