name = "Minecat Neoforge"
author = "Kneelawk"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a9b779fbc4d3e24e3d54f4ca37ca685b1ca3086528be15c98f99c2a09145bc8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.42"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi"
